name: Chrome Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
    
    - name: Get version from manifest
      id: get_version
      run: |
        VERSION=$(grep '"version"' manifest.json | sed -E 's/.*"version": "([^"]+)".*/\1/')
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    
    - name: Check if release exists
      id: check_release
      run: |
        if gh release view "chrome-v${{ env.VERSION }}" >/dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create Chrome extension package
      if: steps.check_release.outputs.exists == 'false'
      run: |
        # Create a temporary directory for the extension files
        mkdir -p temp-chrome-extension
        
        # Copy all necessary files (only if they exist)
        cp manifest.json temp-chrome-extension/
        [ -f background.js ] && cp background.js temp-chrome-extension/
        [ -f content.js ] && cp content.js temp-chrome-extension/
        [ -f styles.css ] && cp styles.css temp-chrome-extension/
        [ -f icon16.png ] && cp icon16.png temp-chrome-extension/
        [ -f icon48.png ] && cp icon48.png temp-chrome-extension/
        [ -f icon128.png ] && cp icon128.png temp-chrome-extension/
        [ -f PrivacyPolicy.md ] && cp PrivacyPolicy.md temp-chrome-extension/
        
        # Create the ZIP file with version in filename
        cd temp-chrome-extension
        zip -r ../chrome-extension-${{ env.VERSION }}.zip .
        
        # Go back to the root directory
        cd ..
        
        # Clean up the temporary directory
        rm -rf temp-chrome-extension
    
    - name: Upload Chrome extension artifact
      if: steps.check_release.outputs.exists == 'false'
      uses: actions/upload-artifact@v4
      with:
        name: chrome-extension-${{ env.VERSION }}
        path: chrome-extension-${{ env.VERSION }}.zip
        retention-days: 30
    
    - name: Create Release
      if: steps.check_release.outputs.exists == 'false'
      run: |
        gh release create "chrome-v${{ env.VERSION }}" \
          --title "Chrome Extension v${{ env.VERSION }}" \
          --notes "Automated release for Chrome Extension v${{ env.VERSION }}" \
          chrome-extension-${{ env.VERSION }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}